### ISSUE TITLE
[bug]: Embedding models not downloaded?

### ISSUE THREAD

**Issue by ga-it** [nextcloud/context_chat_backend#119]
I am sure I must have done something wrong. 

I cleared the old instllation and built the Docker image for 4.0.1

When I run the first context chat query against the backend, I get an embedding error.

I manually downloaded the models and then it worked.
docker logs -f --tail 500 context_chat_backend
Initializing the PostgreSQL database...
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory persistent_storage/vector_db_data/pgsql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default "max_connections" ... 100
selecting default "shared_buffers" ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/17/bin/pg_ctl -D persistent_storage/vector_db_data/pgsql -l logfile start

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
Starting PostgreSQL...
waiting for server to start.... done
server started
Waiting for PostgreSQL to start...
PostgreSQL is up and running.
CREATE ROLE
ALTER ROLE
CREATE DATABASE
CREATE EXTENSION
Running repairs...
No repairs are required.
Detecting hardware...
Detected hardware: CUDA
Copying config file to the persistent storage...
App config:
{
  "debug": true,
  "disable_aaa": false,
  "httpx_verify_ssl": true,
  "use_colors": true,
  "uvicorn_workers": 1,
  "embedding_chunk_size": 2000,
  "doc_parser_worker_limit": 10,
  "vectordb": [
    "pgvector",
    {}
  ],
  "embedding": {
    "protocol": "http",
    "host": "localhost",
    "port": 5000,
    "workers": 1,
    "offload_after_mins": 15,
    "request_timeout": 1800,
    "llama": {
      "model": "multilingual-e5-large-instruct-q6_k.gguf",
      "n_batch": 16,
      "n_ctx": 8192,
      "n_gpu_layers": -1
    }
  },
  "llm": [
    "nc_texttotext",
    {}
  ]
}
INFO:     Started server process [71]
INFO:     Waiting for application startup.
TRACE:    ASGI [1] Started scope={'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}}
TRACE:    ASGI [1] Receive {'type': 'lifespan.startup'}

App enabled at startup
TRACE:    ASGI [1] Send {'type': 'lifespan.startup.complete'}
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:10034 (Press CTRL+C to quit)

TRACE:    192.168.0.73:44014 - HTTP connection made
TRACE:    192.168.0.73:44014 - ASGI [2] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.19.0.2', 10034), 'client': ('192.168.0.73', 44014), 'scheme': 'http', 'method': 'PUT', 'root_path': '', 'path': '/loadSources', 'raw_path': b'/loadSources', 'query_string': b'', 'headers': '<...>', 'state': {}}
TRACE:    192.168.0.73:44014 - ASGI [2] Receive {'type': 'http.request', 'body': '<1448 bytes>', 'more_body': True}
TRACE:    192.168.0.73:44014 - ASGI [2] Receive {'type': 'http.request', 'body': '<13032 bytes>', 'more_body': True}
TRACE:    192.168.0.73:44014 - ASGI [2] Receive {'type': 'http.request', 'body': '<1448 bytes>', 'more_body': True}
....
Embedding sources:
files__default: 8000579 (110416_file1.pdf)
...
files__default: 7997666 (190527_file5.pdf)
Try 0 failed in exception
Try 1 failed in exception
Try 2 failed in exception
Try 3 failed in exception
Try 4 failed in exception
Try 5 failed in exception
Try 6 failed in exception
Try 7 failed in exception
Try 8 failed in exception

___

[Nextcloud Hub 9] (30.0.1)
Nextcloud Assistant Context Chat 4.0.1
context_chat_backend 4.0.1
Remote AppAPI server

**Comment by kyteinsky** [comment]
`Try 0 failed in exception` this is normal, it is waiting for the embedding server to be ready.
Here it seems the internal embedding server has crashed. You can find the logs at `/app/embedding_model.log`. Please care to share.

**Comment by kyteinsky** [comment]
ah damn, it seems to have worked looking at your other issues. Closing this issue, if it's not resolved feel free to revert.

**Comment by ga-it** [comment]
Hi Anupam

Not sure it resolved. Or I gave up too early and downloaded the models myself.

Hence the ability to progress onto the other issues.

**Comment by kyteinsky** [comment]
the logs don't show the registration step happen, it enable automatically so probably it was in some other install.
The register step calls the `/init` endpoint that downloads the model. So if the backend is wiped without app_api knowing, it does not call the apis in an orderly fashion (heartbeat -> init -> enable) for a fresh install (fresh from our perspective).
No init called, no model downloaded.
