### ISSUE TITLE
[bug]: Container reboots on Synology NAS

### ISSUE THREAD

**Issue by stephan1827** [nextcloud/context_chat_backend#42]
The container keeps on restarting on a Synology NAS. I can not see any error message in the logs. I deployed the container within NC AIO as external App. Attached is the error log from the container.

 - Nextcloud Version: 28.0.4 AIO
 - AppAPI Version: 2.4
 - Context Chat PHP Version [e.g. 1.0.0]
 - Context Chat Backend Version 2.1.0
 - Nextcloud deployment method: Docker AIO
 - Context Chat Backend deployment method: one-click

[nc_app_context_chat_backend.txt](https://github.com/nextcloud/context_chat_backend/files/15062311/nc_app_context_chat_backend.txt)

**Comment by kyteinsky** [comment]
Hello, my best guess is that the Synology NAS does not have the required RAM to load the models, which is why the container is being killed over and over again. With the default configuration, 12GB of free RAM is required to run this app.
