### ISSUE TITLE
[feature]: Set timeouts for `exAppRequest` and `exAppRequestWithUserInit` calls

### ISSUE THREAD

**Issue by bigcat88** [nextcloud/context_chat_backend#43]
We will add a default timeout in AppAPI when ContextChat is ready, in this paper we can discuss or just track the progress of Chat Context on this issue.

Reference: https://github.com/cloud-py-api/app_api/pull/277

**Comment by kyteinsky** [comment]
closing issue since we set the timeout for every request. The timeout for deletion requests will be reduced to 3s.
