### ISSUE TITLE
Timeout after 3000008  ms

### ISSUE THREAD

**Issue by Pfeiffenrohr** [nextcloud/context_chat_backend#48]
**Describe the bug**
I installed context_chat at my testserver an this is a little bit slow. So the calcualtion from cotext chat backend takes to lang and I get an timeout after  300000 milliseconds
Is there a way to increase thie timeout?

**To Reproduce**

 See error

**Expected behavior**
increase the timeout.

**Server logs (if applicable)**
Error during request to ExApp context_chat_backend: cURL error 28: Operation timed out after 3000008 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:23000/query","userAgent":"--","version":"29.0.0.19","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Operation timed out after 3000008 milliseconds with 0 bytes received 
```
<paste logs here or attach a file>
```

**Context Chat Backend logs (if applicable, from the docker container)**
Context Chat Backend works fine.

```
<paste logs here or attach a file>
```
</details>

**Screenshots**
I

**Setup Details (please complete the following information):**
 - Nextcloud Version: [eg. 29.0.0, master]
 - AppAPI Version: [eg. 2.5.0]
 - Context Chat PHP Version [e.g. 2.2.1]
 - Context Chat Backend Version [e.g. 2.2.1]
 - Nextcloud deployment method: []
 - Context Chat Backend deployment method: one-click

**Additional context**
It would be enough for me to know if I can increase this timeout by myself.

**Comment by kyteinsky** [comment]
Hello, looks like 50 minutes isn't enough for some cases. I don't think we should increase that further by default. What you could do is set a longer timeout in the app config: `occ config:app:set context_chat request_timeout --value=3000` (value is in seconds)

**Comment by Pfeiffenrohr** [comment]
Thanks for the answer. I try it.

**Comment by Pfeiffenrohr** [comment]
OK. It works fine :) Thanks a lot!

**Comment by kyteinsky** [comment]
You're welcome!
