### ISSUE TITLE
[bug]: hwdetect.sh does not detect GPUs

### ISSUE THREAD

**Issue by ga-it** [nextcloud/context_chat_backend#66]
**Describe the bug**
The hwdetect script greps for "VGA.*NVIDIA" this may not detect all GPUs. It does not pick up Tesla P40s.
I override this with a persistent compose.yaml, but obviously not optimal.

**To Reproduce**
1. Run docker startup:
2. docker run -d --gpus '"device=0,1"' -v /opt/context_chat_backend/config.gpu.yaml:/app/config.yaml -v /data/context_chat_backend/persistent_storage:/app/persistent_storage -v /opt/context_chat_backend/context_chat_backend:/app/context_chat_backend -v /var/run/docker.sock:/var/run/docker.sock --env-file /opt/context_chat_backend.env --name context_chat_backend  -p 10034:10034 context_chat_backend_dev:latest

**Expected behavior**
Correct detection of GPUs

**Relevant code**
<details>
```
# if the COMPUTE_DEVICE env var is not set, try to detect the hardware
if [ -z "$accel" ]; then
	echo "Detecting hardware..."

	lspci_out=$(lspci)
	if echo "$lspci_out" | grep -q "VGA.*NVIDIA"; then
		accel="cuda"
	else
		accel="cpu"
	fi

	echo "Detected hardware: $accel"
fi
```
</details>

**context_chat_backend startup**
<details>
```
Detecting hardware...
Detected hardware: cpu

```
</details>

**GPUs per LSPCI**
<details>
```
 lspci | grep NVIDIA
03:00.0 3D controller: NVIDIA Corporation GP102GL [Tesla P40] (rev a1)
82:00.0 3D controller: NVIDIA Corporation GP102GL [Tesla P40] (rev a1)

```
</details>

**Setup Details (please complete the following information):**
 - Nextcloud Version: [Nextcloud Hub 8]() (29.0.4)
 - AppAPI Version: 3.1.0
 - Context Chat PHP Version 8.2.22
 - Context Chat Backend Version 3.0.1
 - Nextcloud deployment method: Docker latest stable
 - Context Chat Backend deployment method: manual, remote
 - chroma.sqlite3 is 175Gb (nextcloud file repository is TB+)

**Comment by kyteinsky** [comment]
hi, thanks for the report. This should be good enough I guess

```
if echo "$lspci_out" | grep -q "(VGA|3D).*NVIDIA"; then
```
