### ISSUE TITLE
Updates to files in Collectives will not be synchronized to the Context Chat Backend.

### ISSUE THREAD

**Issue by aef5748** [nextcloud/context_chat_backend#72]
1. Install Collectives.
2. Create a new Collective and add the file test_file.md
3. Synchronize the test_file.md file to the Context Chat Backend using php cron.php.
4. Modify test_file.md and run php cron.php to synchronize, but the updated file content is not synchronized to the Context Chat Backend.

**Comment by kyteinsky** [comment]
Hi, how do you verify the synchronization has completed? The cron process indexes files for all the users so the modification would be listed at the bottom of the indexation jobs, Try asking a question with "Selective context" in the assistant to force it to index it on the fly.

**Comment by aef5748** [comment]
Hi,
I did the following test while observing the logs from the context chat backend
- Add the new file to the collection and execute php cron.php manually. I see that the archive is synced to the context chat backend.
- After making modifications to existing files in the collection, save and manually execute php cron.php. After waiting for a long time, I did not see the file synchronized to the context chat backend, but I added an additional file and re-executed php cron.php, and the file will be synchronized to the context chat backend.

If I add a new file or modify it in files, and manually execute php cron.php, I will see that the file is synchronized to the context chat backend. It seems normal, but when using collectives, only added files will be synchronized. context chat backend, modified files will not be synchronized

**Comment by kyteinsky** [comment]
Not sure why that happens since the editors in both files and collectives is the same "text" app, and in my testing it emit the `NodeWrittenEvent` in both the places as expected. To be 100% sure, you can inspect the database of the backend manually. It is located at `/nc_app_context_chat_backend_data/vector_db_data/chroma.sqlite3` inside the container `nc_app_context_chat_backend`. The table `embedding_metadata` will have the desired data.

**Comment by kyteinsky** [comment]
> It seems normal, but when using collectives, only added files will be synchronized. context chat backend, modified files will not be synchronized

thanks for the report! It was an issue in the context_chat php app and fixed in the latest version.
Feel free to revert if it still is an issue.
